import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { NextAuthProvider } from "./lib/next-auth/provider";
import { Suspense } from "react";
import LoadingSpinner from './loading';


const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Book commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={notoSansJP.className}
      >
        <NextAuthProvider>
          <Header />
          {/*データの読み込み中に表示するUIを指定する。fallbackプロパティに指定されたコンポーネントを表示することができる。
          fallbackプロパティに<LoadingSpinner />を指定しているためchildrenコンポーネントが読み込まれる間<LoadingSpinner />が表示される*/}
          <Suspense fallback={<LoadingSpinner />}>
          {children} 
          </Suspense> 
        </NextAuthProvider> 
      </body>
    </html>
  );
}
